FROM python:3-alpine
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
 
# Install the necessary dependencies for apline linux with mysql
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY . /code/

EXPOSE 8000
CMD python /code/manage.py runserver 0.0.0.0:8000